version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: sports-team-recommend-db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: "sports_team_recommend_db"
      TZ: "Asia/Seoul"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
